logging:
  path: ./logs/yupc-admin-server
  file: ${logging.path}/root.log
  common-pattern: '%d{yyyy-MM-dd HH:mm:ss.SSS}:[%5p] [%t:%r] [%C{1}:%M:%L] --> %m%n'
  level:
    console: INFO
    rest: INFO
    service: INFO
    sql: DEBUG

server:
  port: 9765
eureka:
  instance:
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
    prefer-ip-address: true
    status-page-url: http://gateway.yupc.com:9770/api/admin/swagger-ui.html
#    hostname: ${eureka.hostname:eureka.yupc.com}    # 指定该Eureka实例的主机名
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
      management.context-path: ${management.context-path}

spring:
  profiles:
    active: dev
  application:
    name: yupc-admin-server
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  rabbitmq:
    host: yupc.rabbitmq.host
    port: 5672
    password: guest
    username: guest
  redis:
    host: yupc.redis.host
    port: 6379
    pool:
      max-active: 20
      min-idle: 2
      max-idle: 8
      max-wait: 100
    key-prefix: dev
  sleuth:
    sampler:
      percentage: 1
    integration:
      enabled: false
    scheduled:
      skip-pattern: "^org.*HystrixStreamTask$"
  zipkin:
#    base-url: http://yupc-zipkin:8510
    locator:
      discovery:
        enabled: true
    service:
      name: ${spring.application.name}
#    rabbitmq:
#      queue: zipkin

management:
  security:
    enabled: true
  context-path: /mgmt

security:
  basic:
    enabled: true
    path: ${management.context-path}
  user:
    name: admin
    password: ${SECURITY_USER_PASSWORD:admin}
endpoints:
  health:
    enabled: true
    sensitive: true  # actuator的health接口是否需要安全保证

dozer:
  mappingFiles: classpath*:dozer/*.dozer.xml

yupc:
  mysql:
    admin:
      database: yupc_admin_dev       # 根据环境更改
      driverClassName: ${yupc.mysql.driverClassName}
      host: ${yupc.mysql.host}
      password: ${yupc.mysql.password}
      port: ${yupc.mysql.port}
      url: jdbc:mysql://${yupc.mysql.admin.host}:${yupc.mysql.admin.port}/${yupc.mysql.admin.database}?serverTimezone=CTT&characterEncoding=utf8&useUnicode=true&useSSL=false
      username: ${yupc.mysql.username}
    driverClassName: com.mysql.cj.jdbc.Driver  # 6.0.6
#    driverClassName: com.mysql.jdbc.Driver    # 5.x
    host: yupc.mysql.host     # 根据环境更改
    port: 3306                  # 根据环境更改
    username: root              # 根据环境更改
    password: bNVOqb7WKLX5Bjnw+LMv92taj25KOxDimXxILPQjw42wgv+1lHzOH8kr97xDwWdhpY67QuYCS7sWN4W46YbkFA==


feign:
  hystrix:
    enabled: true

hystrix:
  config:
    stream:
      maxConcurrentConnections: 50
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

swagger2:
  package: com.github.yupc.admin.rest
  service:
    name: admin 后台管理 服务
    description: 后台管理服务
    contact:
      name: 最后
      url: http://www.yupc.com/
      email: tangstruggle@sina.com

auth:
  serviceId: yupc-auth-server
  app:
    token-header: token # 其三方应用token
    pub-key:
      path: app/pub.key
  client:
    id: yupc-admin-server
    secret: 123456
    token-header: token
    admin-header: _isAdmin
    pub-key:
      path: client/pub.key

id-generator:
  machine-code: 1  # id生成器机器掩码


