#shiro:
#  realm: com.github.yupc.center.shiro.ShiroAuthorizingRealm
#  loginUrl: http://center.yupc.com:${server.port}/login
#  successUrl: http://center.yupc.com:${server.port}/index
#  unauthorizedUrl: http://center.yupc.com:${server.port}/unauthorized
#  filterChainDefinitions:
#    anon:
#      - /login
#      - /register
#      - /static/**
#      - /mgmt/**
#      - /webjars/**
#    logout:
#      - /logout
#    authc:
#      /**
#
#yupc:
#  variable:
#    gate-way-url-prefix: http://127.0.0.1:9970
#
#server:
#  port: 9740
#
#security:
#  basic:
#    enabled: false
#
#management:
#  security:
#    enabled: false
#
#spring:
#  thymeleaf:
#    cache: false
#  mvc:
#    static-path-pattern: /static/**
#    view:
#      suffix: .html
